# Dockerfile.nginx -- static assets baked in from the built web image; nginx also
# absorbs the routing job upstream's (dropped) haproxy did, see docker/nginx-newsblur.conf.
FROM quay.nekohouse.ca:8443/init/newsblur-app:latest AS appsrc

FROM quay.nekohouse.ca:8443/init/sn-nginx-rh:1.24
USER 0
COPY --from=appsrc /srv/newsblur/media /srv/newsblur/media
COPY --from=appsrc /srv/newsblur/static /srv/newsblur/static
COPY docker/nginx-newsblur.conf /etc/nginx/nginx.conf
RUN mkdir -p /tmp/nginx/client_temp /tmp/nginx/proxy_temp /tmp/nginx/fastcgi_temp \
             /tmp/nginx/uwsgi_temp /tmp/nginx/scgi_temp \
 && chown -R 1001:0 /tmp/nginx /srv/newsblur /etc/nginx/nginx.conf \
 && chmod -R g=u /tmp/nginx /srv/newsblur
USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
